require("./event")
require("./ros")
var Koa = require("koa")
var logger = require("koa-logger")
var cors = require("kcors")
var formatOutput = require("./middleware/format-output")
var rosStatus = require("./middleware/ros-status")
router = require("./middleware/router")("../apis")

var app = new Koa()

app.use(formatOutput())
app.use(rosStatus())
app.use(logger())
app.use(cors())
app.use(router.routes())
app.use(router.allowedMethods())
app.listen(8080)

console.log(`服务已启动在 8080 端口`)
